

// ping youtube selectors
  if( $(YOUTUBE_SELECTORS.APPEND_EXTENTION_TO) != null ){
    console.log(`✅, YOUTUBE_SELECTORS.APPEND_EXTENTION_TO : ${ $(YOUTUBE_SELECTORS.APPEND_EXTENTION_TO) }`)
  }
  else{
    console.log(`🚨, YOUTUBE_SELECTORS.APPEND_EXTENTION_TO : ${ $(YOUTUBE_SELECTORS.APPEND_EXTENTION_TO) }`)
  }

  if( $(YOUTUBE_SELECTORS.COMMENT_HEIGHT_TRACKER) != null ){
    console.log(`✅, YOUTUBE_SELECTORS.COMMENT_HEIGHT_TRACKER : ${ $(YOUTUBE_SELECTORS.COMMENT_HEIGHT_TRACKER) }`)
  }
  else{
    console.log(`🚨, YOUTUBE_SELECTORS.COMMENT_HEIGHT_TRACKER : ${ $(YOUTUBE_SELECTORS.COMMENT_HEIGHT_TRACKER) }`)
  }

  if( $(YOUTUBE_SELECTORS.COMMENTS_WRAPPER) != null ){
    console.log(`✅, YOUTUBE_SELECTORS.COMMENTS_WRAPPER : ${ $(YOUTUBE_SELECTORS.COMMENTS_WRAPPER) }`)
  }
  else{
    console.log(`🚨, YOUTUBE_SELECTORS.COMMENTS_WRAPPER : ${ $(YOUTUBE_SELECTORS.COMMENTS_WRAPPER) }`)
  }

  if( $(YOUTUBE_SELECTORS.COMMENT) != null ){
    console.log(`✅, YOUTUBE_SELECTORS.COMMENT : ${ $(YOUTUBE_SELECTORS.COMMENT) }`)
  }
  else{
    console.log(`🚨, YOUTUBE_SELECTORS.COMMENT : ${ $(YOUTUBE_SELECTORS.COMMENT) }`)
  }

  if( $(YOUTUBE_SELECTORS.PAID_COMMENT) != null ){
    console.log(`✅, YOUTUBE_SELECTORS.PAID_COMMENT : ${ $(YOUTUBE_SELECTORS.PAID_COMMENT) }`)
  }
  else{
    console.log(`🚨, YOUTUBE_SELECTORS.PAID_COMMENT : ${ $(YOUTUBE_SELECTORS.PAID_COMMENT) }`)
  }

  if( $(YOUTUBE_SELECTORS.TROLL_IMG) != null ){
    console.log(`✅, YOUTUBE_SELECTORS.TROLL_IMG : ${ $(YOUTUBE_SELECTORS.TROLL_IMG) }`)
  }
  else{
    console.log(`🚨, YOUTUBE_SELECTORS.TROLL_IMG : ${ $(YOUTUBE_SELECTORS.TROLL_IMG) }`)
  }

  if( $(YOUTUBE_SELECTORS.TROLL_NAME) != null ){
    console.log(`✅, YOUTUBE_SELECTORS.TROLL_NAME : ${ $(YOUTUBE_SELECTORS.TROLL_NAME) }`)
  }
  else{
    console.log(`🚨, YOUTUBE_SELECTORS.TROLL_NAME : ${ $(YOUTUBE_SELECTORS.TROLL_NAME) }`)
  }

  if( $(YOUTUBE_SELECTORS.TROLL_CHANNEL_LINK_NODE) != null ){
    console.log(`✅, YOUTUBE_SELECTORS.TROLL_CHANNEL_LINK_NODE : ${ $(YOUTUBE_SELECTORS.TROLL_CHANNEL_LINK_NODE) }`)
  }
  else{
    console.log(`🚨, YOUTUBE_SELECTORS.TROLL_CHANNEL_LINK_NODE : ${ $(YOUTUBE_SELECTORS.TROLL_CHANNEL_LINK_NODE) }`)
  }

  if( $(YOUTUBE_SELECTORS.SCROLL_TO_BOTTOM_OF_CHECKBOX_BUTTON) != null ){
    console.log(`✅, YOUTUBE_SELECTORS.SCROLL_TO_BOTTOM_OF_CHECKBOX_BUTTON : ${ $(YOUTUBE_SELECTORS.SCROLL_TO_BOTTOM_OF_CHECKBOX_BUTTON) }`)
  }
  else{
    console.log(`🚨, YOUTUBE_SELECTORS.SCROLL_TO_BOTTOM_OF_CHECKBOX_BUTTON : ${ $(YOUTUBE_SELECTORS.SCROLL_TO_BOTTOM_OF_CHECKBOX_BUTTON) }`)
  }

  if( $(YOUTUBE_SELECTORS.LIVE_CHAT_IFRAME_WRAPPER) != null ){
    console.log(`✅, YOUTUBE_SELECTORS.LIVE_CHAT_IFRAME_WRAPPER : ${ $(YOUTUBE_SELECTORS.LIVE_CHAT_IFRAME_WRAPPER) }`)
  }
  else{
    console.log(`🚨, YOUTUBE_SELECTORS.LIVE_CHAT_IFRAME_WRAPPER : ${ $(YOUTUBE_SELECTORS.LIVE_CHAT_IFRAME_WRAPPER) }`)
  }

  if( $(YOUTUBE_SELECTORS.LIVE_CHAT_IFRAME) != null ){
    console.log(`✅, YOUTUBE_SELECTORS.LIVE_CHAT_IFRAME : ${ $(YOUTUBE_SELECTORS.LIVE_CHAT_IFRAME) }`)
  }
  else{
    console.log(`🚨, YOUTUBE_SELECTORS.LIVE_CHAT_IFRAME : ${ $(YOUTUBE_SELECTORS.LIVE_CHAT_IFRAME) }`)
  }

